sppinturas/models/valor_metro_quadrado.py
from sppinturas import db

class ValorMetroQuadradoModel(db.Model):

    __tablename__ = 'valor_do_metro_quadrado'

    id = db.Column(db.Integer, primary_key=True)
    valor = db.Column(db.Float, nullable=False)

    def __init__(self, valor):
        self.valor = valor

    def json(self):
        return {
            'valor': self.valor
        }

    @classmethod
    def find_all(cls):
        return cls.query.all()

    def add_to_db(self):
        db.session.add(self)
        db.session.flush()

    def save_to_db(self):
        db.session.commit()

    def delete_from_db(self):
        db.session.delete(self)
        db.session.commit()

sppinturas/valor_metro_quadrado/forms.py
from flask_wtf import FlaskForm
from wtforms import FloatField, SubmitField
from wtforms.validators import DataRequired

class ValorMetroQuadradoForm(FlaskForm):

    # Valor do metro quadrado
    valor = FloatField('Valor atual', validators=[DataRequired()])

    submit = SubmitField('Enviar')

sppinturas/core/views.py
from flask import Blueprint, render_template

core = Blueprint('core', __name__)

@core.route('/dashboard', methods=['GET'])
def index():
    return render_template('base.html')

sppinturas/materiais/views.py
# Dependencies
from flask import Blueprint, render_template, url_for, redirect, request
from sppinturas import db
# Models
from sppinturas.models.material_disponivel import MaterialDisponivelModel
# Forms
from sppinturas.materiais.forms import MaterialForm

materiais = Blueprint('materiais', __name__)

# 1 - LISTAR MATERIAIS
@materiais.route('/dashboard/listar_materiais', methods=['GET'])
def listar_materiais():

    materiais = MaterialDisponivelModel.find_all()

    return render_template('lista_materiais.html', materiais=materiais)


# 2 - CADASTRAR MATERIAL
@materiais.route('/dashboard/adicionar_material', methods=['GET', 'POST'])
def adicionar_material():

    form = MaterialForm()

    if form.validate_on_submit():

        # Material
        descricao = form.descricao.data

        # 1 - Criando Material - POST

        novo_material = MaterialDisponivelModel(descricao)

        novo_material.add_to_db()
        novo_material.save_to_db()

        return redirect(url_for('materiais.listar_materiais'))

    return render_template('formulario_material.html', form=form, titulo='Novo Material')

# 3 - LER OU ATUALIZAR MATERIAL
@materiais.route('/dashboard/atualizar_material/<int:id_material>', methods=['GET', 'POST'])
def atualizar_material(id_material):

    material = MaterialDisponivelModel.find_by_id(id_material)

    form = MaterialForm()

    if form.validate_on_submit():

        # 1 - Atualizando Material - UPDATE
        material.descricao = form.descricao.data
        db.session.flush()
        db.session.commit()

        return redirect(url_for('materiais.listar_materiais'))

    elif request.method == 'GET':

        # Material
        form.descricao.data = material.descricao

    return render_template('formulario_material.html', form=form, titulo='Atualizar Material')

# 4 - DELETAR MATERIAL
@materiais.route('/dashboard/deletar_material/<int:id_material>', methods=['POST'])
def deletar_material(id_material):

    material = MaterialDisponivelModel.find_by_id(id_material)

    material.delete_from_db()

    return redirect(url_for('materiais.listar_materiais'))

sppinturas/pedidos/views.py
# Dependencies
from flask import Blueprint, render_template, url_for, redirect, request
from sppinturas import db
import datetime
# Models
from sppinturas.models.pedido import PedidoModel
from sppinturas.models.condominio import CondominioModel
from sppinturas.models.sindico import SindicoModel
from sppinturas.models.administradora import AdministradoraModel
# Forms
from sppinturas.pedidos.forms import PedidoForm

pedidos = Blueprint('pedidos', __name__)

# 1 - LISTAR PEDIDOS
@pedidos.route('/dashboard/listar_pedidos', methods=['GET'])
def listar_pedidos():

    pedidos = PedidoModel.find_all()

    datas_formatadas = []
    for pedido in pedidos:
        data_armazenada = pedido.data
        data_em_lista = data_armazenada.split('-')
        data_formatada = f'{data_em_lista[2]}/{data_em_lista[1]}/{data_em_lista[0]}'
        datas_formatadas.append(data_formatada)


    return render_template('lista_pedidos.html', pedidos=pedidos)


# 2 - CADASTRAR PEDIDO
@pedidos.route('/dashboard/adicionar_pedido', methods=['GET', 'POST'])
def adicionar_pedido():

    form = PedidoForm()

    if form.validate_on_submit():

        # Síndico
        nome_do_sindico = form.nome_do_sindico.data
        celular_1_do_sindico = form.celular_1_do_sindico.data
        celular_2_do_sindico = form.celular_2_do_sindico.data
        unwanted_chars = ['(', ')', ' ', '-']
        for c in unwanted_chars:
            celular_1_do_sindico = celular_1_do_sindico.replace(c, '')
            celular_2_do_sindico = celular_2_do_sindico.replace(c, '')
        email_do_sindico = form.email_do_sindico.data

        # Administradora
        nome_da_administradora = form.nome_da_administradora.data
        telefone_1_da_administradora = form.telefone_1_da_administradora.data
        telefone_2_da_administradora = form.telefone_2_da_administradora.data
        unwanted_chars = ['(', ')', ' ', '-']
        for c in unwanted_chars:
            telefone_1_da_administradora = telefone_1_da_administradora.replace(c, '')
            telefone_2_da_administradora = telefone_2_da_administradora.replace(c, '')
        email_da_administradora = form.email_da_administradora.data

        # Condomínio
        nome_do_condominio = form.nome_do_condominio.data
        endereco = form.endereco.data
        numero = form.numero.data
        CEP = form.CEP.data
        numero_de_predios = form.numero_de_predios.data
        numero_de_andares_por_predio = form.numero_de_andares_por_predio.data

        ####################################################################################################

        # 1 - Criando Síndico - POST

        novo_sindico = SindicoModel(nome_do_sindico, celular_1_do_sindico, celular_2_do_sindico, email_do_sindico)
        
        novo_sindico.add_to_db()
        novo_sindico.save_to_db()
        

        # 2 - Criando Administradora - POST

        nova_administradora = AdministradoraModel(nome_da_administradora, telefone_1_da_administradora, telefone_2_da_administradora, 
                                                  email_da_administradora)
        nova_administradora.add_to_db()
        nova_administradora.save_to_db()
        

        # 3 - Criando Condomínio - POST
        
        condominio = CondominioModel.find_by_condominio(nome_do_condominio, endereco, numero, CEP)
        if not condominio:
            novo_condominio = CondominioModel(nome_do_condominio, numero_de_predios, numero_de_andares_por_predio,
                                            endereco, numero, CEP, novo_sindico.id, nova_administradora.id)
            novo_condominio.add_to_db()
            novo_condominio.save_to_db()

        # 4 - Criando Pedido - POST

        data_do_cadastro_do_pedido = datetime.date.today()
        
        try:
            novo_pedido = PedidoModel(data_do_cadastro_do_pedido, 'Recebido', novo_condominio.id)
        except:
            novo_pedido = PedidoModel(data_do_cadastro_do_pedido, 'Recebido', condominio.id)

        novo_pedido.add_to_db()
        novo_pedido.save_to_db()
        
        return redirect(url_for('pedidos.listar_pedidos'))

    return render_template('formulario_pedido.html', form=form)

# 3 - LER OU ATUALIZAR PEDIDO
@pedidos.route('/dashboard/atualizar_pedido/<int:id_pedido>', methods=['GET', 'POST'])
def atualizar_pedido(id_pedido):

    pedido = PedidoModel.find_by_id(id_pedido)
    condominio = CondominioModel.find_by_id(pedido.id_condominio)
    sindico = SindicoModel.find_by_id(condominio.id_sindico)
    administradora = AdministradoraModel.find_by_id(condominio.id_administradora)

    form = PedidoForm()

    if form.validate_on_submit():

        # 1 - Atualizando Condomínio - UPDATE
        
        condominio.nome = form.nome_do_condominio.data
        condominio.endereco = form.endereco.data
        condominio.numero = form.numero.data
        condominio.CEP = form.CEP.data
        condominio.numero_de_predios = form.numero_de_predios.data
        condominio.numero_de_andares_por_predio = form.numero_de_andares_por_predio.data
        db.session.flush()
        db.session.commit()

        # 2 - Atualizando Síndico - UPDATE
        
        sindico.nome = form.nome_do_sindico.data
        sindico.nome = form.celular_1_do_sindico.data
        sindico.nome = form.celular_2_do_sindico.data
        sindico.nome = form.email_do_sindico.data
        db.session.flush()
        db.session.commit()
        
        # 3 - Atualizando Administradora - UPDATE
        
        administradora.nome = form.nome_da_administradora.data
        administradora.nome = form.telefone_1_da_administradora.data
        administradora.nome = form.telefone_2_da_administradora.data
        administradora.nome = form.email_da_administradora.data
        db.session.flush()
        db.session.commit()

        return redirect(url_for('pedidos.listar_pedidos'))

    elif request.method == 'GET':
        
        # Condomínio
        form.nome_do_condominio.data = condominio.nome
        form.endereco.data = condominio.endereco
        form.numero.data = condominio.numero
        form.CEP.data = condominio.CEP
        form.numero_de_predios.data = condominio.numero_de_predios
        form.numero_de_andares_por_predio.data = condominio.numero_de_andares_por_predio

        # Síndico
        form.nome_do_sindico.data = sindico.nome
        form.celular_1_do_sindico.data = sindico.celular_1
        form.celular_2_do_sindico.data = sindico.celular_2
        form.email_do_sindico.data = sindico.email
        
        # Administradora
        form.nome_da_administradora.data = administradora.nome
        form.telefone_1_da_administradora.data = administradora.telefone_1
        form.telefone_2_da_administradora.data = administradora.telefone_2
        form.email_da_administradora.data = administradora.email

    return render_template('formulario_pedido.html', form=form)

# 4 - DELETAR PEDIDO
@pedidos.route('/dashboard/deletar_pedido/<int:id_pedido>', methods=['POST'])
def deletar_pedido(id_pedido):

    pedido = PedidoModel.find_by_id(id_pedido)

    pedido.delete_from_db()

    return redirect(url_for('pedidos.listar_pedidos'))

sppinturas/servicos/views.py
# Dependencies
from flask import Blueprint, render_template, url_for, redirect, request
from sppinturas import db
# Models
from sppinturas.models.servico_disponivel import ServicoDisponivelModel
# Forms
from sppinturas.servicos.forms import ServicoForm

servicos = Blueprint('servicos', __name__)

# 1 - LISTAR SERVIÇOS

@servicos.route('/dashboard/listar_servicos', methods=['GET'])
def listar_servicos():

    servicos = ServicoDisponivelModel.find_all()

    return render_template('lista_servicos.html', servicos=servicos)


# 2 - CADASTRAR SERVIÇO
@servicos.route('/dashboard/adicionar_servico', methods=['GET', 'POST'])
def adicionar_servico():

    form = ServicoForm()

    if form.validate_on_submit():

        # Serviço
        descricao = form.descricao.data

        # 1 - Criando Serviço - POST

        novo_servico = ServicoDisponivelModel(descricao)

        novo_servico.add_to_db()
        novo_servico.save_to_db()

        return redirect(url_for('servicos.listar_servicos'))

    return render_template('formulario_servico.html', form=form, titulo='Novo Serviço')

# 3 - LER OU ATUALIZAR SERVIÇO
@servicos.route('/dashboard/atualizar_servico/<int:id_servico>', methods=['GET', 'POST'])
def atualizar_servico(id_servico):

    servico = ServicoDisponivelModel.find_by_id(id_servico)

    form = ServicoForm()

    if form.validate_on_submit():

        # 1 - Atualizando Serviço - UPDATE
        servico.descricao = form.descricao.data
        db.session.flush()
        db.session.commit()

        return redirect(url_for('servicos.listar_servicos'))

    elif request.method == 'GET':

        # Serviço
        form.descricao.data = servico.descricao

    return render_template('formulario_servico.html', form=form, titulo='Atualizar Serviços')

# 4 - DELETAR SERVIÇO
@servicos.route('/dashboard/deletar_servico/<int:id_servico>', methods=['POST'])
def deletar_servico(id_servico):

    servico = ServicoDisponivelModel.find_by_id(id_servico)

    servico.delete_from_db()

    return redirect(url_for('servicos.listar_servicos'))

sppinturas/valor_metro_quadrado/views.py
# Dependencies
from flask import Blueprint, render_template, url_for, redirect, request
from sppinturas import db
# Models
from sppinturas.models.valor_metro_quadrado import ValorMetroQuadradoModel
# Forms
from sppinturas.valor_metro_quadrado.forms import ValorMetroQuadradoForm

valor_metro_quadrado = Blueprint('valor_metro_quadrado', __name__)

# 1 - VER, CADASTRAR OU ATUALIZAR VALOR DO METRO QUADRADO
@valor_metro_quadrado.route('/dashboard/valor_metro_quadrado', methods=['GET', 'POST'])
def manter_valor_metro_quadrado():

    form = ValorMetroQuadradoForm()
    if request.method == 'GET':
        try:
            lista_valores_registrados = ValorMetroQuadradoModel.find_all()
            valor_registrado = lista_valores_registrados[0].valor
            form.valor.data = valor_registrado
            return render_template('valor_metro_quadrado.html', form=form)
        except:
            return render_template('valor_metro_quadrado.html', form=form)
    elif request.method == 'POST':
        try:
            lista_valores_registrados = ValorMetroQuadradoModel.find_all()
            objeto_valor_registrado = lista_valores_registrados[0]
            valor_atualizado = form.valor.data
            objeto_valor_registrado.valor = valor_atualizado
            db.session.flush()
            db.session.commit()
            return redirect(url_for('valor_metro_quadrado.manter_valor_metro_quadrado'))
        except:
            print('Não atualizou!')
            return redirect(url_for('valor_metro_quadrado.manter_valor_metro_quadrado'))

sppinturas/templates/lista_materiais.html
{% extends "base.html" %}
{% block content %}
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head d-flex align-items-center justify-content-between">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Materiais
                        </h3>
                    </div>
                </div>
                <a href="{{ url_for('materiais.adicionar_material') }}"
                    class="btn btn-outline-primary m-btn m-btn--icon m-btn--outline-2x">
                    <span>
                        <i class="fa fa-plus"></i>
                        <span>
                            Adicionar Material
                        </span>
                    </span>
                </a>
            </div>
            <div class="m-portlet__body pt-1">
                <!-- Campo de Pesquisa da Tabela -->
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-xl-8 order-2 order-xl-1">
                            <div class="form-group m-form__group row align-items-center">
                                <div class="col-md-4">
                                    <div class="m-form__group m-form__group--inline">
                                        <div class="m-form__label">
                                            <label>
                                                Status:
                                            </label>
                                        </div>
                                        <div class="m-form__control">
                                            <select class="form-control m-bootstrap-select" id="m_form_status">
                                                <option value="">
                                                    Todos
                                                </option>
                                                <option value="1">
                                                    Recebido
                                                </option>
                                                <option value="2">
                                                    Enviado
                                                </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="d-md-none m--margin-bottom-10"></div>
                                </div>
                                <div class="col-md-4">
                                    <div class="m-input-icon m-input-icon--left">
                                        <input type="text" class="form-control m-input" placeholder="Procurar..."
                                            id="generalSearch">
                                        <span class="m-input-icon__icon m-input-icon__icon--left">
                                            <span>
                                                <i class="la la-search"></i>
                                            </span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Fim de Campo de Pesquisa da Tabela -->

                <!-- Tabela -->
                <table class="m-datatable" id="html_table" width="100%">
                    <!-- Cabeçalho da Tabela -->
                    <thead>
                        <tr>
                            <th title="Field #1">
                                Id
                            </th>
                            <th title="Field #2">
                                Descrição
                            </th>
                            <th title="Field #3">
                                Ações
                            </th>
                        </tr>
                    </thead>
                    <!-- Fim de Cabeçalho da Tabela -->
                    <!-- Corpo da Tabela -->
                    <tbody>
                        {% for material in materiais %}
                        <!-- Linha da Tabela -->
                        <tr>
                            <!-- Coluna 1 -->
                            <td>
                                {{ material.id }}
                            </td>
                            <!-- Fim de Coluna 1 -->

                            <!-- Coluna 2 -->
                            <td>
                                {{ material.descricao }}
                            </td>
                            <!-- Fim de Coluna 2 -->

                            <!-- Coluna 3 - Editar ou Excluir -->
                            <td>
                                <form action="{{ url_for('materiais.atualizar_material', id_material=material.id) }}"
                                    class="container-edit-button">
                                    <button type="submit" class="edit-button">
                                        <i class="flaticon-edit"></i>
                                    </button>
                                </form>
                                <div class="container-delete-button">
                                    <button type="submit" class="delete-button" id={{material.id}}
                                        onclick="openModal(this, 'deletar_material')">
                                        <i class="flaticon-delete-1"></i>
                                    </button>
                                </div>
                            </td>
                            <!-- Fim de Coluna 5 - Editar ou Excluir -->
                        </tr>
                        <!-- Fim de Linha da Tabela -->
                        {% endfor %}
                    </tbody>
                    <!-- Fim de Corpo da Tabela -->
                </table>
                <!-- Fim de Tabela -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

sppinturas/templates/lista_pedidos.html
{% extends "base.html" %}
{% block content %}
<div class="m-grid__item m-grid__item--fluid m-wrapper">
	<div class="m-content">
		<div class="m-portlet m-portlet--mobile">
			<div class="m-portlet__head d-flex align-items-center justify-content-between">
				<div class="m-portlet__head-caption">
					<div class="m-portlet__head-title">
						<h3 class="m-portlet__head-text">
							Pedidos
						</h3>
					</div>
				</div>
				<a href="{{ url_for('pedidos.adicionar_pedido') }}"
					class="btn btn-outline-primary m-btn m-btn--icon m-btn--outline-2x">
					<span>
						<i class="fa fa-plus"></i>
						<span>
							Adicionar Pedido
						</span>
					</span>
				</a>
			</div>
			<div class="m-portlet__body pt-1">
				<!-- Campo de Pesquisa da Tabela -->
				<div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
					<div class="row align-items-center">
						<div class="col-xl-8 order-2 order-xl-1">
							<div class="form-group m-form__group row align-items-center">
								<div class="col-md-4">
									<div class="m-form__group m-form__group--inline">
										<div class="m-form__label">
											<label>
												Status:
											</label>
										</div>
										<div class="m-form__control">
											<select class="form-control m-bootstrap-select" id="m_form_status">
												<option value="">
													Todos
												</option>
												<option value="1">
													Recebido
												</option>
												<option value="2">
													Enviado
												</option>
											</select>
										</div>
									</div>
									<div class="d-md-none m--margin-bottom-10"></div>
								</div>
								<div class="col-md-4">
									<div class="m-input-icon m-input-icon--left">
										<input type="text" class="form-control m-input" placeholder="Procurar..."
											id="generalSearch">
										<span class="m-input-icon__icon m-input-icon__icon--left">
											<span>
												<i class="la la-search"></i>
											</span>
										</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Fim de Campo de Pesquisa da Tabela -->

				<!-- Tabela -->
				<table class="m-datatable" id="html_table" width="100%">
					<!-- Cabeçalho da Tabela -->
					<thead>
						<tr>
							<th title="Field #1">
								Id
							</th>
							<th title="Field #2">
								Condomínio
							</th>
							<th title="Field #3">
								Data
							</th>
							<th title="Field #4">
								Status
							</th>
							<th title="Field #5">
								Ação
							</th>
						</tr>
					</thead>
					<!-- Fim de Cabeçalho da Tabela -->
					<!-- Corpo da Tabela -->
					<tbody>
						{% for pedido in pedidos %}
						<!-- Linha da Tabela -->
						<tr>
							<!-- Coluna 1 -->
							<td>
								{{ pedido.id }}
							</td>
							<!-- Fim de Coluna 1 -->

							<!-- Coluna 2 -->
							<td>
								{{ pedido.condominio.nome }}
							</td>
							<!-- Fim de Coluna 2 -->

							<!-- Coluna 3 -->
							<td>

								{{ pedido.data.split('-')[2] }}/{{ pedido.data.split('-')[1] }}/{{ pedido.data.split('-')[0] }}
							</td>
							<!-- Fim de Coluna 3 -->

							<!-- Coluna 4 -->
							<td>
								{% if pedido.status == "Recebido" %}
								1
								{% elif pedido.status == "Enviado" %}
								2
								{% endif %}
							</td>
							<!-- Fim de Coluna 4 -->

							<!-- Coluna 5 - Editar ou Excluir -->
							<td>
								<form action="{{ url_for('pedidos.atualizar_pedido', id_pedido=pedido.id) }}"
									class="container-edit-button">
									<button type="submit" class="edit-button">
										<i class="flaticon-edit"></i>
									</button>
								</form>
								<div class="container-delete-button">
									<button type="submit" class="delete-button" id={{pedido.id}}
										onclick="openModal(this, 'deletar_pedido')">
										<i class="flaticon-delete-1"></i>
									</button>
								</div>
							</td>
							<!-- Fim de Coluna 5 - Editar ou Excluir -->
						</tr>
						<!-- Fim de Linha da Tabela -->
						{% endfor %}
					</tbody>
					<!-- Fim de Corpo da Tabela -->
				</table>
				<!-- Fim de Tabela -->
			</div>
		</div>
	</div>
</div>
{% endblock %}

sppinturas/templates/lista_servicos.html
{% extends "base.html" %}
{% block content %}
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head d-flex align-items-center justify-content-between">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Serviços
                        </h3>
                    </div>
                </div>
                <a href="{{ url_for('servicos.adicionar_servico') }}"
                    class="btn btn-outline-primary m-btn m-btn--icon m-btn--outline-2x">
                    <span>
                        <i class="fa fa-plus"></i>
                        <span>
                            Adicionar Serviço
                        </span>
                    </span>
                </a>
            </div>
            <div class="m-portlet__body pt-1">
                <!-- Campo de Pesquisa da Tabela -->
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-xl-8 order-2 order-xl-1">
                            <div class="form-group m-form__group row align-items-center">
                                <div class="col-md-4">
                                    <div class="m-form__group m-form__group--inline">
                                        <div class="m-form__label">
                                            <label>
                                                Status:
                                            </label>
                                        </div>
                                        <div class="m-form__control">
                                            <select class="form-control m-bootstrap-select" id="m_form_status">
                                                <option value="">
                                                    Todos
                                                </option>
                                                <option value="1">
                                                    Recebido
                                                </option>
                                                <option value="2">
                                                    Enviado
                                                </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="d-md-none m--margin-bottom-10"></div>
                                </div>
                                <div class="col-md-4">
                                    <div class="m-input-icon m-input-icon--left">
                                        <input type="text" class="form-control m-input" placeholder="Procurar..."
                                            id="generalSearch">
                                        <span class="m-input-icon__icon m-input-icon__icon--left">
                                            <span>
                                                <i class="la la-search"></i>
                                            </span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Fim de Campo de Pesquisa da Tabela -->

                <!-- Tabela -->
                <table class="m-datatable" id="html_table" width="100%">
                    <!-- Cabeçalho da Tabela -->
                    <thead>
                        <tr>
                            <th title="Field #1">
                                Id
                            </th>
                            <th title="Field #2">
                                Descrição
                            </th>
                            <th title="Field #3">
                                Ações
                            </th>
                        </tr>
                    </thead>
                    <!-- Fim de Cabeçalho da Tabela -->
                    <!-- Corpo da Tabela -->
                    <tbody>
                        {% for servico in servicos %}
                        <!-- Linha da Tabela -->
                        <tr>
                            <!-- Coluna 1 -->
                            <td>
                                {{ servico.id }}
                            </td>
                            <!-- Fim de Coluna 1 -->

                            <!-- Coluna 2 -->
                            <td>
                                {{ servico.descricao }}
                            </td>
                            <!-- Fim de Coluna 2 -->

                            <!-- Coluna 3 - Editar ou Excluir -->
                            <td>
                                <form action="{{ url_for('servicos.atualizar_servico', id_servico=servico.id) }}"
                                    class="container-edit-button">
                                    <button type="submit" class="edit-button">
                                        <i class="flaticon-edit"></i>
                                    </button>
                                </form>
                                <div class="container-delete-button">
                                    <button type="submit" class="delete-button" id={{servico.id}}
                                        onclick="openModal(this, 'deletar_servico')">
                                        <i class="flaticon-delete-1"></i>
                                    </button>
                                </div>
                            </td>
                            <!-- Fim de Coluna 5 - Editar ou Excluir -->
                        </tr>
                        <!-- Fim de Linha da Tabela -->
                        {% endfor %}
                    </tbody>
                    <!-- Fim de Corpo da Tabela -->
                </table>
                <!-- Fim de Tabela -->
            </div>
        </div>
    </div>
</div>
{% endblock %}